In [1]:
import numpy as np
import pandas as pd

In [2]:
cars=pd.read_csv("cars.csv")

In [3]:
cars.head(17)

       brand  km_driven    fuel         owner  selling_price
0     Maruti     145500  Diesel   First Owner         450000
1      Skoda     120000  Diesel  Second Owner         370000
2      Honda     140000  Petrol   Third Owner         158000
3    Hyundai     127000  Diesel   First Owner         225000
4     Maruti     120000  Petrol   First Owner         130000
5    Hyundai      45000  Petrol   First Owner         440000
6     Maruti     175000     LPG   First Owner          96000
7     Maruti       5000  Petrol  Second Owner          45000
8     Toyota      90000  Diesel   First Owner         350000
9       Ford     169000  Diesel   First Owner         200000
10   Renault      68000  Diesel  Second Owner         500000
11    Maruti     100000  Petrol  Second Owner          92000
12    Maruti     140000  Diesel  Second Owner         280000
13    Maruti      80000  Petrol  Second Owner         200000
14    Maruti      90000  Petrol  Second Owner         180000
15  Mahindra      40000  Petrol   First Owner         400000
16    Maruti      70000  Diesel  Second Owner         778000

In [8]:
cars["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [9]:
cars["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [6]:
cars["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
cars["brand"].nunique()

32

By using Pandas dummy method

In [4]:
pd.get_dummies(cars , columns= ["fuel" ,"owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

By using n-1 method drop 1st one..

In [5]:
pd.get_dummies(cars , columns= ["fuel" ,"owner"] ,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train ,x_test ,y_train ,y_test = train_test_split(cars.iloc[:,:4] ,cars.iloc[:,-1] , test_size=0.3 ,random_state=42)

OneHotEncoding using sklearn

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
oht=OneHotEncoder(drop="first" ,sparse_output=False ,dtype=np.int32)

In [23]:
oht.fit(x_train[["fuel" ,"owner"]])

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse_output=False)

In [27]:
x_train_new=oht.transform(x_train[["fuel" ,"owner"]])

In [28]:
x_test_new=oht.transform(x_test[["fuel" ,"owner"]])

In [29]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Maruti', 120000, 0, ..., 0, 0, 1],
       ['Toyota', 100000, 1, ..., 0, 0, 0],
       ['BMW', 39000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

 OneHotEncoding with Top Categories

In [33]:
cars["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [36]:
counts=cars["brand"].value_counts()

In [37]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [38]:
cars["brand"].nunique()

32

In [39]:
threshold = 100

In [40]:
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(cars['brand'].replace(repl, 'uncommon')).sample(5)